<?php
// $Id$


/**
* Implementation of hook_nodeapi
*/

function joury_sc_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){
	switch($op){
			case 'insert' :
			if($node->type == 'sc'){
				$name = $node->title ; 
				$nid = $node->nid ; 
				$description = $node->body ; 
				db_query("insert into {joury_sc} (`nid` , `name` , `description`)  values (%d , '%s', '%s')" , $nid, $name, $description); 
			}		
			break; 		
			
			case 'update' :
			if($node->type == 'sc'){
				$name = $node->title ; 
				$nid = $node->nid ; 
				db_query("update  {joury_sc} set  `name` = '%s' ,`description` = '%s'  where `nid` = %d " ,  $name , $description,$nid); 
			}		
			break;
			
			case 'delete' :
			if($node->type == 'sc'){
				$name = $node->title ; 
				$nid = $node->nid ; 
				db_query("delete from  {joury_sc} where `nid` = %d " , $nid); 
			}		
			break;
		
		
		}	
}




/**
* Implementation of hook_jourymenu
*/

function joury_sc_jourymenu(){
	return array(
	'service-categories',
	'joury_sc',
	array('scid' => 'id','name' => 'name','description' => 'description'),
	array(),
	'',
	'',
	); 	
}