<?php
// $Id$


/**
* Implementation of hook_nodeapi
*/

function joury_showrooms_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){
	switch($op){
			case 'insert' :
			if($node->type == 'showrooms'){
				$name = $node->title ; 
				$nid = $node->nid ;
				$description = $node->body ; 
				$center = node_load($node->field_showroomcenter[0]['nid']) ;

				db_query("insert into {joury_showrooms} (`center`,`nid` , `name` , `description`)  values ('%s', %d , '%s' , '%s')" ,$center->title, $nid, $name, $description); 
				include_once './includes/bootstrap.inc';
				drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
				drupal_flush_all_caches();
			}			
			break; 		
			
			case 'update' :
			if($node->type == 'showrooms'){
				$name = $node->title ;
				$nid = $node->nid ;
				$description = $node->body ;
				$center = node_load($node->field_showroomcenter[0]['nid']) ;
				db_query("update  {joury_showrooms} set `center`  = '%s' ,  `name` = '%s', `description` = '%s'  where `nid` = %d ",$center->title, $name,$description , $nid); 
			}	
			break;
			
			case 'delete' :
			if($node->type == 'showrooms'){
				$name = $node->title ; 
				$nid = $node->nid ; 
				db_query("delete from  {joury_showrooms} where `nid` = %d " , $nid); 
			}		
			break;
			
			case 'view' :

			break ; 		
		
		}	
}






/**
* Implementation of hook_jourymenu
*/

function joury_showrooms_jourymenu(){
	return array(
	'showrooms',
	'joury_showrooms',
	array('sid' => 'showroom id','name' => 'name'),
	array(),
	'',
	'',
	); 	
}


/**
* Private function to get showroom name from showroom id 
*/

function _get_showroom_name_from_id($showroomid){
	$result_handle = db_query("select name from `joury_showrooms` where `sid`= %d" , $showroomid);
	$result_obj = db_fetch_object($result_handle) ; 
	$name = $result_obj->name ; 
	return $name ; 	
	}
