<?php
// $Id$

/**
* Implementation of hook_menu() . 
*/
function joury_staff_attendance_menu() {
	$menu['joury/staff/attendance/import']	= array(
		'title' => t('Import staff Data') , 
		'page callback' => '_joury_staff_attendance_import' ,
		'access arguments' => array('staff attendance- import csv data') ,
		'type' => MENU_NORMAL_ITEM,
	);
	$menu['joury/get/months/options'] = array(
		'access arguments' => array('access content') , 
		'page callback' =>  '_path_get_months_options', 
		'type' => MENU_CALLBACK, 
	); 

	return $menu ; 
}	

/**
* Implementation of hook_perm().
*/
function joury_staff_attendance_perm() {
	return array("staff attendance- import csv data");	
}


/**
* Implementation of hook_theme()
*/
function joury_staff_attendance_theme() {
	return array(
	  'theme_joury_staff_attendance_import' => array(
	  		'arguments' => array(1) , 
	  		'template' => 'page_joury_staff_attendance_import' , 
	  ),
	);	
}	

/**
* get months options
*/
function _path_get_months_options() {
	$year = $_POST['year'] ; 
	$months = _get_months_options($year) ; 
	
  $form_state = array('storage' => NULL, 'submitted' => FALSE);
  $form_build_id = $_POST['form_build_id'];
  // Step #4.
  $form = form_get_cache($form_build_id, $form_state);

  // Preparing for #5.
  $args = $form['#parameters'];
  $form_id = array_shift($args);
  $form_state['post'] = $form['#post'] = $_POST;
  $form['#programmed'] = $form['#redirect'] = FALSE;
  
  // Step #6 and #7 and #8.
  $form = drupal_rebuild_form($form_id, $form_state, $args, $form_build_id);
  $form['container']['month']['#options'] = $months ; 
  // Step #9.
  $month_form = $form['container']['month'];
  unset($choice_form['#prefix'], $choice_form['#suffix']);
  $output = theme('status_messages') . drupal_render($month_form);

  // Final rendering callback.
  drupal_json(array('status' => TRUE, 'data' => $output));
}	

/**
* Import page form 
*/
function _form_joury_staff_attendance_import($form_state) {
	$months_options	= _get_months_options(date("Y", time())) ; 
	for($k = 1995 ;  $k < 2040 ; $k++ ) {
		$year_options[$k] = $k ; 	
	}	 
	
	$form['#attributes'] = array('enctype' => "multipart/form-data");	
	$form['container'] = array(
		'#type' => 'fieldset' , 
		'#collapsible' => TRUE, 
		'#title' => t('IMPORT CONFIGURATION') , 
	);
	$form['container']['spacewrapper'] = array(
		'#type' => 'markup' , 
		'#value' => "<div id='space-wrapper' ></div>",
	);	
	$form['container']['year'] = array(
		'#title' => t('year') , 
		'#type' => 'select' , 
		'#default_value' => date("Y", time()) ,
		'#ahah' => array(
      	'path' => 'joury/get/months/options',
     		'wrapper' => 'month-select-options',
		),
		'#options' => $year_options ,
	);
	$form['container']['month'] = array(
		'#title' => t('month') , 
		'#type' => 'select' , 
		'#prefix' => "<div id='month-select-options'>",
		'#suffix' => "</div>" , 
		'#options' => $months_options, 
	);			
	$form['container']['csv_file'] = array(
		'#type' => 'file' ,  
		'#title' => t('csv FILE') , 
		'#description' => t('insert your csv file here') , 
	) ;	
	$form['container']['submit'] = array(
		'#type' => 'submit' ,  
		'#value' => t('SEND') , 
	) ;		
	
	return $form ; 
}


/**
* get months options
*/
function _get_months_options($year) {
	$months = array() ; 
	$current_year = $year ; 
	$months[''] = t('select-month');
	for($k=1 ; $k < 13 ; $k++ ) {
	$result_handler =  db_query("select count(*) from {joury_staff_attendance_date} where `year` = %d  and `month` = %d ", $current_year, $k) ;	
	$result_arr = db_fetch_array($result_handler) ; 
	if($result_arr['count(*)'] == 0) {
	$months[$k] = $k ; 	
	}else{
	$months[$k] = $k." -- inserted" ;	
	}		
	}
	return $months; 
}	


/**
* Import page form validate
*/
function _form_joury_staff_attendance_import_validate($form, $form_state) {
	$extensions = 'csv' ; 
	$validators = array(
		'file_validate_extensions' => array($extensions),
	);
	if(empty($form['#post']['month'])) {
		form_set_error('month' , 'Please select the month') ; 	
	}
	if(!file_save_upload('csv_file', $validators)) {
		form_set_error('csv_file', 'Please select the csv file') ; 	
	}else{
		$file = file_save_upload('csv_file', $validators, file_directory_path()) ; 

		if($file->filemime != 'text/csv' ) {
			form_set_error('csv_file', 'Extensions Allowed : csv') ; 		
		}		
	}		
}


/**
* Import page form submit
*/
function _form_joury_staff_attendance_import_submit($form, $form_state) {
	$file = file_save_upload('csv_file', $validators, file_directory_path()) ; 
	$file_handler = fopen($file->filepath, 'r') ; 
	$line_num = 0 ;
	$fields = array() ;  
	while(!feof($file_handler)) {
		$line_num++ ; 
		$line = fgets($file_handler) ;
		$line_array = explode(",", $line);
		$field_num = 0 ; 
		foreach($line_array as $field) {
			$field_num++ ; 
			$fields[$line_num][$field_num] = str_replace('"', '', $field );	
		}	
	}
	fclose($file_handler);
	unlink($file->filepath);
 	$first_row = $fields[1] ; 	
	if($first_row[1] == 'ID' && $first_row[2] == 'date' &&  $first_row[3] == 'time' && $first_row[4] == 'SerialNo' && $first_row[5] == 'TransType' && $first_row[6] == 'pin' && $first_row[7] == 'finger' && count($first_row) == 8) {
		unset($fields[1]) ; 		
		$k = 2 ; 
		for ($k =2 ; $k <= count($fields) ; $k++ ) {
			if(($fields[$k][5] != 7 && $fields[$k][5] != 8) || count($fields[$k]) < 8 ) {
				unset($fields[$k]) ; 	
				continue;
			}
			$new_fields[] = $fields[$k] ; 
		}

		foreach ($new_fields as $field) {
			if($field[5] == 7 || $field[5] == 8) {
				$action_time = substr($field[3],11,1000) ; 
				$action_date = $field[2] ; 
				$employee_id = $field[6] ;
				$center_ip = (string) $field[8] ;  
				$center_ip = (int) substr($center_ip,10,1) ; 
				
				if($center_ip == 2 ) {
					$center = "Hawalli"	 ;
				}elseif($center_ip == 3) {	
					$center = "Avenues"	 ;
				}elseif($center_ip == 4 ) { 
					$center = "Al Shohadaa"	 ;
				}else{
					$center = "-" ; 
				}	

				$action = $field[5] ; 
				$action_timestamp = strtotime($action_time);
				$action_datestamp = strtotime($action_date);
				$year = date("Y" , $action_datestamp) ;
				$month =  date("m" , $action_datestamp) ;
				$day = date("d" , $action_datestamp) ;
				
				$time = date("h:i A" , $action_timestamp) ;  
				static $new_data = 0; 
				static $deleted_data = 0 ; 
				if($year == $form['#post']['year'] && $month == $form['#post']['month']) {
					$deleted_row = db_query("delete from {joury_staff_attendance} where `employee_id` = %d and `year` = %d and `month` =  %d and `day` = %d and `transaction` = %d"
					,$employee_id, $year, $month, $day, $action) ; 
					$num_of_del_r = db_affected_rows($deleted_row) ; 
					db_query("insert into {joury_staff_attendance} 
					(`center`, `employee_id`, `year`, `month`, `day`, `time`, `transaction`) 
					values
					('%s', %d, %d, %d, %d, '%s', %d)",
					$center, $employee_id, $year, $month, $day, $time, $action); 
					if($num_of_del_r < 1) {
					$new_data++ ; 
					}else{
					$deleted_data++ ; 	
					}		
									
				}
			}
		}
		if($new_data > 0) {
			db_query("delete from {joury_staff_attendance_date} where `year` = %d and  `month` = %d ",$form['#post']['year'], $form['#post']['month']) ; 
			db_query("insert into {joury_staff_attendance_date} (`year`, `month`) values (%d, %d)", $form['#post']['year'], $form['#post']['month']); 
			drupal_set_message("<div class='message ok'>DONE <br/> NEW ROWS : {$new_data} <br/> ROWS EXIST BEFORE/DUBLICATED : {$deleted_data} </div>") ; 
		}else {
			drupal_set_message("<div class='message error'>NEW ROWS : {$new_data} <br/> ROWS EXIST BEFORE/DUBLICATED : {$deleted_data}   <br/><p style='font-size:9px;'> please make sure that the date inside your csv file is different then the date you have selected here</p> </div>") ;
		}
	}else {
		form_set_error('csv_file', 'Wrong table name.. Please insert the  csv file of the table name Transaction') ;	
	}	
	
}




/**
* _joury_staff_attendance_import
*/
function _joury_staff_attendance_import() {
	return theme('theme_joury_staff_attendance_import') ;
}	
